import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../../components/SessionWrapper";
import { ThemeProvider } from "../../components/theme-provider";
import { ClerkProvider, SignIn, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <SessionWrapper>
        <html lang="en">
          <body className={inter.className}>
            <header className="flex justify-between">
              <UserButton showName />
            </header>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              >
                <SignedOut>
                  <SignIn routing="hash" />
                </SignedOut>
                <SignedIn>
                  {children}
                </SignedIn>
            </ThemeProvider>
          </body>
        </html>
      </SessionWrapper>
    </ClerkProvider>
  );
}
